language: java

jdk:
  - oraclejdk8

env:
  global:
    # ARTIFACTORY_API_KEY
    - secure: "WS0CXs5AbxhJR+NCsvlvbkqL79/2flWZ2SJ8CeoPxlVdkviOGSrLg5V+edEciAJFe/8SvFBfTG+ESaeze2TGwVJrv6IpBvDiJxkC63AigjbbCHAPWsxCGHIq3DfG9K+ZDU2L1wNSOa6rWEfPQdIrnL/nELTWGNrqiqikCNqpBergwdmlghT54h4Qmyi/IWvmVagb2SoUxLMUUbzga8Kkc/ajfmJx5dKV4WyOADeojP0Dgv+ZQyEIy2SQOAw7hf4wO8DHWiTnWqzg0OgUHaExFZx/cjgtRyKyBf4zZ4w3QcfXbAPwX7Cczyql+zfGmm4Ge+Cx5gayhVtXtpfB45rZKDv3gsXQ130a3fLgRDCcBixqbz5tOzwEcQezL+Xz13ue2u0c7BOObglJ5HZPlsNKwDSuJEaNEYI0Dd9yoB+3Qf5YeJSKNRfRRGuMQn0ZGXUiMTL3X9gGIBA2p86CWuHicQgk0wtLu0pvXnrGH4C+JDmHCxEGYV+nHvTrG7Xy4e7cqoCIuhLAP6ofv25i7MARzl0olMHWJtOfVoh+xU3jfr0+T5b8DpqSlfcKjE5TV5mWvsSg9WizEDaKrIS6bzucDx5tPI/8XbLzTbzC7AiLHKQql2wKhXbt6LjrfB5/UMrHmRE83k7FlEEfGovufAIh7WsfchMd7oQpIHoal8w0xUs="

install:
  - pip install --user --upgrade sphinx==1.7.9 semantic-version requests urllib3[secure]
  - curl -fL https://getcli.jfrog.io | sh

script:
  - sudo cp fastconnect.org.crt /usr/local/share/ca-certificates/
  - sudo update-ca-certificates
  - export M2_HOME=/usr/local/maven
  - set -e
  - ./jfrog rt c --apikey="${ARTIFACTORY_API_KEY}" --user=travis --url=https://ystia.jfrog.io/ystia ystia
  - ./jfrog rt mvn "clean verify -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true" src/main/resources/artifactory/maven_config_file.yaml --build-name="yorc-a4c-plugin-mvn-travis-ci" --build-number="${TRAVIS_BUILD_NUMBER}"
  - ./jfrog rt bag "yorc-a4c-plugin-mvn-travis-ci" "${TRAVIS_BUILD_NUMBER}" .
  - ./jfrog rt bp "yorc-a4c-plugin-mvn-travis-ci" "${TRAVIS_BUILD_NUMBER}"

before_deploy:
  - "bash ./src/main/resources/bintray/pre_bintray_release.sh"

deploy:
  - provider: script
    script: bash src/main/resources/artifactory/deploy_artifactory.sh
    on:
      all_branches: true
    skip_cleanup: true

  - provider: releases
    overwrite: true
    file_glob: true
    api_key:
      secure: kXuP0Wz/tvm+F5pdCqSC2rRTiWIdVbnqxImeOn/1MfIYekcYkKjEfKO0UnL/FCJJ1MdNmZ6Q5Yn8aTZiUBXZeRiKLs/C2ka7cnwyGjXq2vykc11bPqr44o1J+sNuq85nxtKLIfXK+I4AfcmlBtofDVEBi6FFb+YXPFJRlowDqqbReKv8se0Ik5vcARBhrO/I30GuWP8Pf8AaiSrBYDvln1DazPKekR/mq3vhh5pW/WPfZW/gscXtuBUDU67eAhgh9JFLk/LiOOXNbnuQD2bfkFztZRVLbyt/FfJJHv78MXFslcGIvMR6wsG8WaPQuYh/36L1025dnIdFp7zranqlgk/heObzEOsyd+zb2yQyQJIan252EZbruf9m2/HlaiFR32QdQ6aSTa4JFbmp4e6FHxkU1eOerPiHMJwzelG1BXQaDBlo/5rfJSNGAOQmUAj13Kem2U3DcL8eQ7nfQaCTr0d7iOQTTxkzouSkIr3du5VlisaxR4zn+1MrxELmYBXNIpYCXOyqgpDRxLZ6dmBsNBMMcyFlzxULkfoSMb4DDiMyqlDddexcakvkqwzC6X5SmZCwRMQvZmVdsqupHS/KaiJWjGhl0ahIaCEUtW+jveVPScIGc0Vmje3Lnx8uh+Keuqu8Sr2uraVG/VVInYJsVKuVYNKD+8HLPxyXnZZVpig=
    file:
      - distribution/target/alien4cloud-yorc-plugin-distribution-*.zip
      - alien4cloud-yorc-plugin/target/alien4cloud-yorc-plugin-*.zip
    skip_cleanup: true
    on:
      tags: true
    
  - provider: bintray
    file: "src/main/resources/bintray/bintray_release.json"
    user: "loicalbertin"
    key: 
      secure: "P2mLECuyFKhwiqpXootyPhYXEj4p8L/ewpMmuzZWZxl3wjIS/Mz0Q8n6QpdUD9FD758E8aUYb0UyioeeiLtzKxdJaHzpQFAmstZxhzr0DTaqdkNuF38+XWtYydDp8nKQd3A2234155vKlFp5GxBZXCCm96RuwH/b3Q46fyHvaNNeg0s2eacvQtxvor9aG0WiocPoGqypUoArv1rYHRZ9Nt3Yiu52jkOpvaoQAHB7Jzh3qBnSjWXeSSy+wPydiywK57jtJZsmUyVTX1wuPjlzeUGnrfx05f+JfPVybOU2CK5tQ4OVmwxWM/Lp/XkmKOgW1+/tf/sF6RP1KEnwEaFzPdtN7CWai+WXAyCMX4yJNkUiqkCTqs2I+DqwZYzIDqk/Xdt8i2yN8QAf4zqNS0zfS/SvS+3sqTzc62wBMZL0Rz5yPu3YFCplPdP8xdQbxHjXvi1x+P1bYTNbIV0Trj5XlZ/gA8uC8TVt1H7Ay2C5K/+aHIZ8XVuQlcPl6TSyF9vJpCiHd+ugnsAXHkYXP0N9ybGmhB35dZL6dgnb9pnEaPBrFvFyTSWe+ZCLOZpMc9jlTsWjzVgVjdtqqWjXEHGyCVLPGYBZnyFlRKJokNiNXPHUa1k1mT6rvZO3VFF5sVxa8d0jPLI1FtKMSlgamWp7F/NcdFX24+iL3p8KG3Ol40g="
    skip_cleanup: true
    on:
      tags: true


addons:
  apt:
    packages:
    - jq
    - latexmk
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended

cache:
  directories:
    - $HOME/.m2/repository

