language: java

jdk:
  - oraclejdk8

install:
  - pip install --user --upgrade sphinx semantic-version requests urllib3[secure]

script:
  - mvn clean install

deploy:
  - provider: script
    script: bash deploy.sh
    on:
      all_branches: true
    skip_cleanup: true

  - provider: releases
    overwrite: true
    api_key:
      secure: ZHIdTaOa3MbxENL2spVhKk3P3DatNXZ5hjg+4oe0hCdZsr1feb0WnC4jsfMeU5rQcaiwJEWknrvdq66RUQvbcOtEr/SIrPUplc/qjWiH6i81lELX1OVp41M1YSkjEKnjCUqyW1lcBCS8KgwaiNCRd6BI6BbPhNy4bO0ssQXnT8wuaWaPExgjo8qck9qsB7n+Ta0gwkHd9Ly3FdH1I4DmcwB1T0kB9MRjmJk5WeX8uBN7vJjcrsy8VbDwLxTRhjAbLSz7Pa7fUBtA4ssXJQbbAxpXaaa8FkkBPLXCf+zsq6+Cqnhj/Y8O360iu92A6hgNKUkCCNqXJHxYP6L6ETY/wh+6XlnWKWPSCy3/z5KFJYptVDD70EStKhHj3Gwjyh0mXGGt4UpgMBZlTzj2I0uReS6BCGcJ3t0/ny3L0x4LhnQpNGsgzm/2CiLfr0PUcBgAI4b6jUpzfZlG9H7DfiwHJdhU1yTbelBjf4nYEAG2oQVijD9wSiMyTShWt6Hh4Vw1WsGemd14TzOdDP6eAbECqjAb6OIpe8edeiD/fdwXoXFCdmMHuq19XXGloCOgJpfExxByagZhN8SsFxsr5mUdnSSuXUZ3XtcoRhCum7J7ZsTIJ6nhS6DrvVjI9Hwiq2d3IK10JgQ6K48C/c0qW+TvOUJvgmeQCHpSF+gLJWQlodY=
    file:
      - distribution/target/alien4cloud-yorc-plugin-distribution-*.zip
      - alien4cloud-yorc-plugin/target/alien4cloud-yorc-plugin-*.zip
    skip_cleanup: true
    on:
      tags: true

addons:
  apt:
    packages:
    - latexmk
    - texlive-binaries
    - texlive-fonts-recommended
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
