id: alien4cloud-Janus-paas-provider
name: Hpc PaaS provider
version: ${project.version}
description: >
  Plugin that contains a single paas provider for deployments' mocking.
configuration_class: alien4cloud.plugin.Janusus.HpcPaaSProviderPluginConfiguration
component_descriptors:
  - bean_name: Janus-orchestrator-factory
    name: Hpc Orchestrator Factory
    description: >
      Orchestrator Factory that instanciate orchestrators that just mocks deployment.
      Used for our automated tests the plugin suceed for every application except an application named:
       - BAD-APPLICATION: The deployment will fail.
       - WARN-APPLICATION: The deployment will ends up in a warning state.
