id: alien4cloud-Janus-plugin
name: Janus PaaS provider
version: 1.0.0
description: >
  Plugin that contains a single paas provider for deployments on Hpc env.
configuration_class: alien4cloud.plugin.Janus.JanusPluginConfiguration
component_descriptors:
  - bean_name: Janus-orchestrator-factory
    name: Janus Orchestrator Factory
    description: >
      Orchestrator Factory that instanciate orchestrators that just deployment a topology given by A4C.
      Used for our automated tests the plugin suceed for every application except an application named:
       - BAD-APPLICATION: The deployment will fail.
       - WARN-APPLICATION: The deployment will ends up in a warning state.
