tosca_definitions_version: alien_dsl_1_3_0

template_name: janus-kubernetes-types
template_author: Janus
template_version: ${janus.types.version}

imports:
  - janus-docker-types:${janus.types.version}

artifact_types:
  tosca.artifacts.Deployment.Image.Container.Docker.Kubernetes:
    description: Docker Container Image
    derived_from: tosca.artifacts.Deployment.Image.Container.Docker