tosca_definitions_version: alien_dsl_1_3_0

template_name: janus-kubernetes-types
template_author: Janus
template_version: ${janus.types.version}

imports:
  - tosca-normative-types:1.0.0-ALIEN12
  - janus-types:${janus.types.version}

node_types:
  janus.nodes.KubernetesContainer:
    derived_from: janus.nodes.DockerContainer