#
# Starlings
# Copyright (C) 2015-2016 Bull S.A.S. - All rights reserved
#
- name: Connects consul agent to consul server
  hosts: all
  strategy: free
  become: yes
  become_user: consul
  become_method: sudo
  vars:
    consul_servers: []
  tasks:
    - name: compute consul servers
      set_fact: 
        consul_servers: "{{ consul_servers }} + [ '{{ hostvars[inventory_hostname][item] }}' ]"
      with_items: "{{ hostvars[inventory_hostname]  }}"
      when: item | match(TARGET_NODE+'_.*_SERVER_IP')

    - name: Install servers config for consul
      template: 
        src: 2_connects_to_servers.json.j2
        dest: "{{CONFIG_DIR}}/2_connects_to_servers.json"
    
    - name: echo servers list
      debug: msg="Consul Agent configured to connects to server on [{{ consul_servers | join(', ') }}]"
